# Generated by Django 4.1.1 on 2022-09-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='cat',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location',
            field=models.CharField(max_length=128),
        ),
    ]
